# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Repos\HBCustomLib\scripts\designer\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 121)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(0, 121))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 121))
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.le_folderPath = QtWidgets.QLineEdit(self.centralwidget)
        self.le_folderPath.setObjectName("le_folderPath")
        self.horizontalLayout.addWidget(self.le_folderPath)
        self.btn_selectPath = QtWidgets.QPushButton(self.centralwidget)
        self.btn_selectPath.setObjectName("btn_selectPath")
        self.horizontalLayout.addWidget(self.btn_selectPath)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.btn_addData = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addData.setObjectName("btn_addData")
        self.verticalLayout_3.addWidget(self.btn_addData)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 694, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HB Lib Customiser"))
        self.le_folderPath.setPlaceholderText(_translate("MainWindow", "选择生成路径: ..\\ladybug_tools\\resources\\standards"))
        self.btn_selectPath.setText(_translate("MainWindow", "选择"))
        self.btn_addData.setText(_translate("MainWindow", "生成库文件夹"))
